// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qrjwerfavremzncdadcv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFyandlcmZhdnJlbXpuY2RhZGN2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4NzY2MDAsImV4cCI6MjA3MzQ1MjYwMH0.BA8UsQPpCUeGuZ4EYknkhQxS6T-novrJXOaYZkJ1Sfg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});